### ISSUE TITLE
WIKI/DOCUMENTATION: Wanting to contribute

### ISSUE THREAD

**Issue by TheEvilSkeleton** [lutris/docs#3] opened 2020-03-13 23:35 UTC
Hello, I want to contribute for the [Lutris wiki](https://github.com/lutris/lutris/wiki), but I have seen a lot of problems that I can't just create a merge request get over with. The [Installing drivers](https://github.com/lutris/lutris/wiki/Installing-drivers) section is just terribly made in my opinion, and I would like to know if it can be changed to "Installing Lutris" or "Installing" so I can easily work on the documentation. I am aware that there is a tutorial in the [home](https://lutris.net/downloads/) page, but I feel like it is good to make it easy and coherent rather than make people switch websites.

I saw [CONTRIBUTING.md](https://github.com/lutris/lutris/blob/master/CONTRIBUTING.md), and it also does not tell you any information about documentations, which is what I want to contribute for. since the documentations for Lutris are in my opinion... bad.

**Comment by TheEvilSkeleton** [comment] 2020-03-27 23:42
@tannisroot what are your thoughts on this? https://github.com/TheEvilSkeleton/lutris-wiki-fork/blob/master/awesome-gnu-linux-gaming.md

**Comment by TheEvilSkeleton** [comment] 2020-04-08 23:59
Nevermind

**Comment by tannisroot** [comment] 2020-04-09 17:05
Moved all pages to this repository. Going to resolve all issues with them next, however if you want you are free to help. Sorry it took so long btw, kinda got caught up in my own stuff.

**Comment by TheEvilSkeleton** [comment] 2020-04-09 18:38
Don't worry, and sorry for being a bit too impatient.

**Comment by TheEvilSkeleton** [comment] 2020-04-09 18:42
Also, just wondering, I've seen the [Lutris downloads](https://lutris.net/downloads/), and that alone looks unfinished. I am wondering if we can merge [InstallingDrivers.md](https://github.com/lutris/docs/blob/master/InstallingDrivers.md) with the downloads page.

**Comment by tannisroot** [comment] 2020-04-09 22:39
Well, the issue is that downloads page is an html page, and our documentation files are in markdown. So if we create a duplicate of it, we will have to write a completely new page and keep them synced, and to me it would required more time than it's worth. And no, personally I want to keep them separated. I do plan however to make a summary of those pages on lutris wiki, and I can link to the Downloads page in it to make some sort of a complete step by step guide, if that's what you want.

**Comment by TheEvilSkeleton** [comment] 2020-04-09 23:54
Sure

**Closed** 2020-05-24 22:09 UTC
