### ISSUE TITLE
Cant install battlenet on lutris

### ISSUE THREAD

**Issue by dartvini** [lutris/docs#144] opened 2023-06-21 02:56 UTC
when i try to install battlenet via lutris i get error 256, then after trying again i get error 136. and i cant install idk what to do!!!

**Comment by Ejdesgaard** [comment] 2023-06-25 13:44
When I try to install battlenet from lutris.net/games/battlenet, I get the following warning:
```
warning: /home/user/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "wine: WINEARCH set to win64 but '/home/hedin/Games/battlenet' is a 32-bit installation." 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```

**Comment by Ejdesgaard** [comment] 2023-06-25 14:11
I resolved the issue.
The problem was that ~/Games/battlenet/ had settings for win32 instead of win64.
I moved the drive_c/program files (x86) folder out of ~/Games/battlenet/, then I deleted ~/Games/battlenet.
Then I tried to install battlenet again and is succedded.
Lastly, I overwrote the newly created  "program files (x86)" folder in ~/Games/battlenet, with the initial one.
On first start of battlenet, after this, it found all the games.

**Comment by JakubVyhnalek** [comment] 2023-07-18 07:26
> when i try to install battlenet via lutris i get error 256, then after trying again i get error 136. and i cant install idk what to do!!!

Same problem here.

**Comment by vansharora03** [comment] 2023-07-28 01:08
Same here, I get exit code 136

**Comment by strycore** [comment] 2023-07-31 18:09
No one on the Lutris team can reproduce this issue. We all have working installations of Battle.net on multiple computers.

We're going to need more details if you wish to have a fix some day.

**Comment by romanovzky** [comment] 2023-08-08 07:33
I have this issue, what would you need from me to help debug?

**Comment by strycore** [comment] 2023-08-08 23:37
we need someone with 1 working setup and 1 non working setup (whether it is a dual boot or on another machine). Once we have that, we can work out the differences between those systems.

**Comment by decryp7** [comment] 2023-08-09 03:32
I got the error 136 and managed to resolve the issue by downloading and using the correct wine version as default.
Beside the "Wine" menu item under "Runners", there are 2 buttons. 
First icon to manage and download the wine versions.
Second icon is to select the wine version you want to use.
Please refer to my screenshots.

![Screenshot_20230809_111547](https://github.com/lutris/docs/assets/12887997/f7b8c230-bbdd-4aec-a861-53aa016723d9)
![Screenshot_20230809_111449](https://github.com/lutris/docs/assets/12887997/395f6564-6449-4c72-94c1-597135d6b684)
![Screenshot_20230809_111519](https://github.com/lutris/docs/assets/12887997/ba4a39c9-70b1-47ae-880a-d57f3a9ba2b2)

**Comment by strycore** [comment] 2023-08-09 03:35
The Lutris client using the wrong Wine version is a known bug in 0.5.13 that has already been addressed in the current code.
It seems from the errors in this report that some people are still seeing failure despite using the correct Wine build.

**Comment by romanovzky** [comment] 2023-08-09 11:15
For me it was the case of wrong Wine version being used. So I can't help anymore as my problem is fixed now...

**Comment by strycore** [comment] 2023-08-10 02:33
Going to mark this issue as resolved as it's unlikely that we'll get more details and current Lutris code + Wine build works fine.

**Closed by strycore** 2023-08-10 02:33 UTC

**Comment by TooManyStacks** [comment] 2023-10-01 09:47
Ubuntu 22.04, Lutris 0.5.13, trying to install battle.net, gives me the following(136 first time 256 afterwards). Tell me which data I need to give more.









Started initial process 20278 from /home/user/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: cf1e17a69db4126779e597def9facdecbb0703a20ed7172dd877b1f7824d66ec with wine-7.2-1-g2b48f296545 (Staging) and WINEARCH=win64
Executing w_do_call arial
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_arial 
Executing cabextract -q -d /home/user/Games/battlenet/dosdevices/c:/windows/temp /home/user/.cache/winetricks/corefonts/arial32.exe
------------------------------------------------------
warning: Running /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/home/user/Games/battlenet terminate
------------------------------------------------------
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
fsync: up and running.
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_304f5183_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_964415d4_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_1f616c49_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_16f0ad00_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_afb17c0c_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_4cd1fddd_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_dae52f18_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_f89c822c_20278.reg
Executing cabextract -q -d /home/user/Games/battlenet/dosdevices/c:/windows/temp /home/user/.cache/winetricks/corefonts/arialb32.exe
------------------------------------------------------
warning: Running /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/home/user/Games/battlenet terminate
------------------------------------------------------
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
fsync: up and running.
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_66d0267b_20278.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.Suzg7An7/_reg_8067e78b_20278.reg
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Started initial process 21479 from /home/user/.local/share/lutris/runtime/winetricks/winetricks --unattended tahoma
Start monitoring process.
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20230212-next - sha256sum: cf1e17a69db4126779e597def9facdecbb0703a20ed7172dd877b1f7824d66ec with wine-7.2-1-g2b48f296545 (Staging) and WINEARCH=win64
Executing w_do_call tahoma
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_tahoma 
Executing cabextract -q -d /home/user/Games/battlenet/dosdevices/c:/windows/temp /home/user/.cache/winetricks/tahoma/IELPKTH.CAB
/home/user/.cache/winetricks/tahoma/IELPKTH.CAB: WARNING; possible 5592 extra bytes at end of file.
------------------------------------------------------
warning: Running /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/home/user/Games/battlenet terminate
------------------------------------------------------
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
fsync: up and running.
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.C6sblbHO/_reg_a6378261_21479.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.C6sblbHO/_reg_2381d506_21479.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.C6sblbHO/_reg_21e53125_21479.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine64 C:\windows\regedit.exe /S C:\windows\Temp\_register-font.reg
Executing cp /home/user/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.C6sblbHO/_reg_4779f8a8_21479.reg
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Started initial process 22423 from /usr/bin/bash -c WINEESYNC=1 WINEPREFIX=/home/user/Games/battlenet /home/user/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine /home/user/Games/battlenet/drive_c/Battle.net-Setup.exe
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 136)
All processes have quit
Exit with return code 136
